name: Lint files

on:
  pull_request:
  push:
    trigger:
      branches:
        include:
          - main
          - dev-*
          - feat-*

  jobs:
    lint_files:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
        - with:
            node-version: [16.x]

        - run: npm ci

        - name: lint
          run: npm run lint
