name: CI - Runs ESLint, Prettier, and Cypress, Jest test files

on:
  push:
    branches: [main]

  pull_request:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Run all jobs
        run: |
          echo "____________Starting CI _________________"

      - name: Checkout #1
        uses: actions/checkout@v2

      # cypress ___tests___
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          build: npm run build
          config: pageLoadTimeout=100000,baseUrl=http://localhost:3003
          start: npm run dev

      # lint
      - name: Run ESLint #4
        run: npm run lint

      # prettier after
      - name: Prettier #5
        run: npm run prettier

      # jest ___tests___
      - name: Jest run #7
        run: npm test

      - name: Jobs done #8
        run: |
          echo "___________All Jobs done! _________________"
