name: CI - Runs ESLint, Prettier, and  Jest test files

on:
  push:
    branches: [main]

  pull_request:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Run all jobs
        run: |
          echo "____________Starting CI _________________"

      - name: Checkout #1
        uses: actions/checkout@v2

      # lint
      - name: Run ESLint #4
        run: npm run lint

      # prettier after
      - name: Prettier #5
        run: npm run prettier

      # jest ___tests___
      - name: Jest run #7
        run: npm test

      - name: Jobs done #8
        run: |
          echo "___________All Jobs done! _________________"
