name: CI - Runs Prettier, Cypress and Jest test files

on:
  push:
    branches: [main]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Run all jobs
        run: |
          echo "____________Starting CI _________________"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache

          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Node setup
        uses: actions/setup-node@v2
        with:
          node-version: '14.19.3'

      - name: NPM install
        run: npm install

      - name: Prettier
        run: npm run prettier:fix

      # run cypress ___tests___
      - name: E2E ___tests___
        uses: cypress-io/github-action@v4
        with:
          build: npm run build
          start: npm run start
          wait-on: http://localhost:3003

      # jest ___tests___ same as cy
      - name: Jest run
        run: npm test

      - name: Jobs done
        run: |
          echo "___________All Jobs done! _________________"
