name: CI - Runs ESLint, Prettier, and Cypress, Jest test files

on:
  push:
    branches: [main]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Run all jobs
        run: |
          echo "____________Starting CI _________________"

      - name: Checkout #1
        uses: actions/checkout@v3

      - name: Node setup #2
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: NPM install #3
        run: npm install

      # lint
      - name: Run ESLint #4
        run: npm run lint

      # prettier after
      - name: Prettier #5
        run: npm run prettier

      # cypress ___tests___
      - name: E2E ___tests___ #6
        uses: cypress-io/github-action@v4
        with:
          build: npm run build
          start: npm run start
          wait-on: http://localhost:3003

      # jest ___tests___
      - name: Jest run #7
        run: npm test

      - name: Jobs done #8
        run: |
          echo "___________All Jobs done! _________________"
